import test from 'node:test';
import assert from 'node:assert/strict';
import {selectionLevel,parentCommune,populationProfile,housingProfile,equipmentProfile,incomeProfile,employmentProfile,observationValue} from '../src/territory.js';
import {parseCsv,groupTransactions,dvfCodes,transactionsForParcel,loadMarket} from '../src/market.js';
import {handleMarketRequest,marketSource} from '../server/market-api.js';
const obs=(dimensions,value,status='A')=>({dimensions,attributes:{OBS_STATUS:status},measures:{OBS_VALUE_NIVEAU:{value}}});
test('first click shows commune, next same-commune click shows parcel, outside resets context',()=>{assert.equal(selectionLevel(null,'69123'),'commune');assert.equal(selectionLevel('69123','69123'),'parcel');assert.equal(selectionLevel('69123','95127'),'commune');assert.equal(selectionLevel(null,'95127',true),'parcel');});
test('municipal arrondissement codes map to correct parent communes',()=>{assert.equal(parentCommune('69382'),'69123');assert.equal(parentCommune('75120'),'75056');assert.equal(parentCommune('13216'),'13055');assert.equal(parentCommune('2A004'),'2A004');assert.equal(parentCommune('95127'),'95127');assert.equal(dvfCodes('69123').length,9);assert.equal(dvfCodes('75056').length,20);});
test('suppressed values and missing values are never zero',()=>{assert.equal(observationValue(obs({},0,'C')),null);assert.equal(observationValue(obs({},null)),null);assert.equal(observationValue(obs({},0)),0);});
test('population chooses latest period and avoids adding overlapping age bands',()=>{const data={observations:[obs({TIME_PERIOD:'2017',AGE:'_T',SEX:'_T',RP_MEASURE:'POP'},100),obs({TIME_PERIOD:'2023',AGE:'_T',SEX:'_T',RP_MEASURE:'POP'},120),obs({TIME_PERIOD:'2023',AGE:'Y_GE65',SEX:'_T',RP_MEASURE:'POP'},30),obs({TIME_PERIOD:'2023',AGE:'Y65T79',SEX:'_T',RP_MEASURE:'POP'},20)]};const p=populationProfile(data);assert.equal(p.total,120);assert.equal(p.year,'2023');assert.equal(p.ages.length,7);assert.equal(p.ages.find(x=>x.label==='65–79 ans').value,20);assert.equal(p.history.length,2);});
test('housing uses total tenancy for counts and principal residences for owners share',()=>{const base={TIME_PERIOD:'2023',TDW:'_T',TSH:'_T'};const d={observations:[obs({...base,OCS:'_T'},200),obs({...base,OCS:'DW_MAIN'},100),obs({...base,OCS:'DW_MAIN',TSH:'100'},40),obs({...base,OCS:'DW_VAC'},0)]};const p=housingProfile(d);assert.equal(p.ownerShare,40);assert.equal(p.total,200);assert.equal(p.vacant,0);assert.equal(p.secondary,null);});
test('equipment selects domain totals, without double-counting detailed types',()=>{const d={observations:[obs({TIME_PERIOD:'2025',FACILITY_DOM:'C',FACILITY_SDOM:'_T',FACILITY_TYPE:'_T',BPE_MEASURE:'FACILITIES'},8),obs({TIME_PERIOD:'2025',FACILITY_DOM:'C',FACILITY_SDOM:'C1',FACILITY_TYPE:'C101',BPE_MEASURE:'FACILITIES'},2)]};assert.equal(equipmentProfile(d).rows.find(r=>r.label==='Enseignement').value,8);});
test('DVF CSV handles quotes and deduplicates mutation amounts across parcels',()=>{const rows=parseCsv('id_mutation,date_mutation,nature_mutation,valeur_fonciere,id_parcelle,type_local\n1,2025-01-01,Vente,300000,A,"Maison, dépendance"\n1,2025-01-01,Vente,300000,B,Maison\n');const transactions=groupTransactions(rows);assert.equal(transactions.length,1);assert.equal(transactions[0].value,300000);assert.deepEqual(transactions[0].parcels,['A','B']);assert.equal(transactionsForParcel({transactions},'B').length,1);});
test('ambiguous mutation values are not guessed or summed',()=>{const t=groupTransactions([{id_mutation:'1',date_mutation:'2025',valeur_fonciere:'20'},{id_mutation:'1',date_mutation:'2025',valeur_fonciere:'30'}]);assert.equal(t[0].value,null);});
test('DVF missing regional coverage makes no network requests',async()=>{const d=await loadMarket({code:'67482',codeDepartement:'67'});assert.equal(d.status,'not-covered');});
test('market gateway rejects arbitrary destinations, malformed codes and writes',async()=>{assert.equal(marketSource('https://internal'),null);assert.equal(marketSource('../123'),null);assert.equal(marketSource('67482'),null);assert.ok(marketSource('2A004').includes('/2A/2A004.csv'));assert.equal((await handleMarketRequest(new Request('https://app.test/api/market?code=95127&url=https://internal'))).status,400);assert.equal((await handleMarketRequest(new Request('https://app.test/api/market?code=95127',{method:'POST'}))).status,405);});
test('market gateway streams only a verified CSV from the fixed source',async()=>{const result=await handleMarketRequest(new Request('https://app.test/api/market?code=95127'),async url=>{assert.equal(url,'https://files.data.gouv.fr/geo-dvf/latest/csv/2025/communes/95/95127.csv');return new Response('id_mutation,id_parcelle\n1,A\n');});assert.equal(result.status,200);assert.ok((await result.text()).startsWith('id_mutation,'));});

test('market gateway follows only the verified public DVF storage redirect',async()=>{
 let calls=0;const response=await handleMarketRequest(new Request('https://app.test/api/market?code=2A004'),async url=>{calls++;if(calls===1)return new Response(null,{status:302,headers:{location:'https://geo-dvf.s3.sbg.io.cloud.ovh.net/latest/csv/2025/communes/2A/2A004.csv'}});assert.equal(url,'https://geo-dvf.s3.sbg.io.cloud.ovh.net/latest/csv/2025/communes/2A/2A004.csv');return new Response('id_mutation,id_parcelle\n1,A\n');});assert.equal(response.status,200);assert.equal(calls,2);
});
test('market gateway rejects off-domain redirect without fetching it',async()=>{let calls=0;const r=await handleMarketRequest(new Request('https://app.test/api/market?code=29019'),async()=>{calls++;return new Response(null,{status:302,headers:{location:'https://example.com/private'}});});assert.equal(r.status,502);assert.equal(calls,1);});
test('income respects units, suppressed observations, and actual zero poverty',()=>{const d={observations:[obs({TIME_PERIOD:'2023',FILOSOFI_MEASURE:'MED_SL',UNIT_MEASURE:'EUR_YR'},null,'O'),obs({TIME_PERIOD:'2023',FILOSOFI_MEASURE:'PR_MD60',UNIT_MEASURE:'PT'},0)]};assert.equal(incomeProfile(d).median,null);assert.equal(incomeProfile(d).poverty,0);});
test('employment represents residents in work, not local job counts',()=>{const base={TIME_PERIOD:'2023',EMPSTA_ENQ:'1',AGE:'Y_GE15',SEX:'_T',EMPFORM:'_T',RP_MEASURE:'POP'};const d={observations:[obs({...base,WKTIME:'_T'},100),obs({...base,WKTIME:'FT'},80),obs({...base,WKTIME:'PT'},20)]};assert.deepEqual(employmentProfile(d),{year:'2023',total:100,fullTime:80,partTime:20});});
