import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowLeft,Users,MapTrifold,ArrowUpRight} from '@phosphor-icons/react';
import {normalize} from './search.js';
import {Diagnostic} from './Diagnostic.jsx';
import {CommunePortrait} from './CommunePortrait.jsx';
import {MapView} from './MapView.jsx';
import {SearchBox} from './SearchBox.jsx';
import {getJson} from './diagnostic.js';
import {fmt,parentCommune,selectionLevel} from './territory.js';
export function App(){
 const [communes,setCommunes]=useState([]),[loading,setLoading]=useState(true),[city,setCity]=useState(null),[point,setPoint]=useState(null),[parcels,setParcels]=useState([]),[isochrone,setIsochrone]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[level,setLevel]=useState('commune'),[focusVersion,setFocusVersion]=useState(0);
 const pending=useRef(),selection=useRef(null);selection.current=city;
 useEffect(()=>{const controller=new AbortController();getJson('/communes.json',{signal:controller.signal}).then(data=>{if(controller.signal.aborted)return;const list=data.map(c=>({...c,key:normalize(c.nom)}));setCommunes(list);const code=new URLSearchParams(location.search).get('commune');if(code)setCity(list.find(c=>c.code===code)||null);}).catch(()=>{if(!controller.signal.aborted)setError('Impossible de charger le référentiel. Rechargez la page.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>{controller.abort();pending.current?.abort();};},[]);
 function chooseCommune(c){pending.current?.abort();setBusy(false);setCity(c);setLevel('commune');setPoint(null);setParcels([]);setIsochrone(null);setError('');saveUrl(c.code);}
 function saveUrl(code){const url=new URL(location.href);url.searchParams.set('commune',code);history.replaceState({},'',url);}
 async function choosePoint({lat,lng,label},directAddress=false){
  if(loading)return;pending.current?.abort();const controller=new AbortController();pending.current=controller;setBusy(true);setError('');
  try{const data=await getJson(`https://geo.api.gouv.fr/communes?lat=${lat}&lon=${lng}&fields=code`,{signal:controller.signal});if(controller.signal.aborted)return;
   const c=communes.find(c=>c.code===parentCommune(data[0]?.code||''));if(!c){setError('Choisissez un lieu situé en France métropolitaine.');return;}
   const nextLevel=selectionLevel(selection.current?.code,c.code,directAddress);
   setCity(c);setLevel(nextLevel);setPoint(nextLevel==='parcel'?{lat,lon:lng,label:label||'Point sélectionné sur la carte'}:null);setParcels([]);setIsochrone(null);saveUrl(c.code);
  }catch{if(!controller.signal.aborted)setError('La localisation est momentanément indisponible. Réessayez.');}finally{if(!controller.signal.aborted)setBusy(false);}
 }
 function exploreParcel(){setError('');setFocusVersion(v=>v+1);document.getElementById('carte')?.scrollIntoView({behavior:'smooth',block:'start'});}
 function backToCommune(){pending.current?.abort();setBusy(false);setLevel('commune');setPoint(null);setParcels([]);setIsochrone(null);setError('');}
 return <main>
 <header className="masthead"><a className="brand" href="./" aria-label="CartoKob, accueil">CartoKob<span>COMPRENDRE LES TERRITOIRES<br/>POUR AGIR DEMAIN</span></a><SearchBox communes={communes} loading={loading} selectionLabel={point?.label||city?.nom||''} onSelect={c=>c.address?choosePoint({lat:c.lat,lng:c.lon,label:c.nom},true):chooseCommune(c)}/><div className="brand-note"><span>LE TERRITOIRE<br/>LE QUARTIER<br/>LA PARCELLE</span><img src="/france.svg" alt="France métropolitaine"/><span>UN LIEU.<br/>LES BONNES<br/>QUESTIONS.</span></div></header>
 <div role="status" className={error||busy?'status visible':'status'}>{busy?'Localisation de votre sélection…':error}</div>
 {city&&<nav className="journey" aria-label="Niveau de lecture"><button className={level==='commune'?'selected':''} aria-current={level==='commune'?'step':undefined} onClick={backToCommune}>01 · {city.nom}</button><ArrowRight size={15}/><button className={level==='parcel'?'selected':''} aria-current={level==='parcel'?'step':undefined} onClick={()=>point?setLevel('parcel'):exploreParcel()}>02 · {point?'La parcelle':'Choisir une parcelle'}</button><span>{level==='commune'?'Découvrez la commune, puis cliquez à l’intérieur.':'Diagnostic du point sélectionné'}</span></nav>}
 <MapView city={city} point={point} parcels={parcels} isochrone={isochrone} onPoint={choosePoint} focusVersion={focusVersion}/>
 {city?<><section className="summary" aria-live="polite"><div className="place"><p className="eyebrow">{level==='commune'?'LE TERRITOIRE À LA LOUPE':'LE BIEN DANS SON TERRITOIRE'}</p><div className="place-title"><h1 className={city.nom.length>16?'long':city.nom.length>9?'medium':''}>{city.nom}</h1><span>{city.codeDepartement}</span></div><p className="place-sub">{point?point.label:city.departement.nom}<br/><span className="point-instruction">{point?`${point.lat.toFixed(5)}° N · ${point.lon.toFixed(5)}° E`:city.region.nom}</span></p></div><article className="fact"><span className="fact-icon green"><Users size={28}/></span><div><p className="eyebrow">VIE LOCALE</p><h2>{city.population!=null?`${fmt(city.population)} habitants`:'Population indisponible'}</h2><p>Les habitants, les logements et les services : découvrez le contexte de votre futur lieu de vie.</p><a href="https://geo.api.gouv.fr/" target="_blank" rel="noreferrer">API Découpage administratif <ArrowUpRight size={13}/></a></div></article><article className="fact"><span className="fact-icon peach"><MapTrifold size={28}/></span><div><p className="eyebrow">{level==='parcel'?'VOTRE SÉLECTION':'GÉOGRAPHIE'}</p><h2>{level==='parcel'?(parcels.length?`${parcels.length} parcelle${parcels.length>1?'s':''} identifiée${parcels.length>1?'s':''}`:'Diagnostic en dessous'):city.surface!=null?`${fmt(city.surface/100,1)} km² de territoire`:'Un territoire à explorer'}</h2><p>{level==='parcel'?'Urbanisme, servitudes, risques et environnement au même endroit.':'Un clic à l’intérieur de la commune ouvre le diagnostic du terrain.'}</p><span className="data-note">Code commune : {city.code}</span></div></article></section>
 <div className="report-area" id="informations"><div hidden={level!=='commune'}><CommunePortrait key={city.code} city={city} onExplore={exploreParcel}/></div>{level==='parcel'&&point&&<section className="parcel-report"><button className="text-button back-link" onClick={backToCommune}><ArrowLeft size={16}/>Retour au portrait de {city.nom}</button><Diagnostic key={`${city.code}:${point.lat},${point.lon}`} city={city} point={point} onGeometry={setParcels} onIsochrone={setIsochrone}/></section>}</div></>:<section className="welcome"><p className="eyebrow">VOTRE PROCHAIN LIEU DE VIE</p><h1>Une commune à découvrir.<br/>Un terrain à comprendre.</h1><p>Cliquez sur la carte ou recherchez une adresse. Commencez par le territoire, puis entrez dans le détail de la parcelle.</p></section>}
 <footer><div className="signature">Atlas éditorial <span>—</span> CartoKob</div><span className="edition">France métropolitaine <span>·</span> Version de travail</span></footer>
 </main>
}
