import React,{useEffect,useRef,useState,useMemo} from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import {MagnifyingGlass,ArrowRight,X,Plus,Minus,Crosshair,Users,MapTrifold,ArrowUpRight,MapPin,Compass} from '@phosphor-icons/react';
import markerUrl from 'leaflet/dist/images/marker-icon.png';
import markerRetinaUrl from 'leaflet/dist/images/marker-icon-2x.png';
import markerShadow from 'leaflet/dist/images/marker-shadow.png';
import {normalize,searchCommunes} from './search';
import {Diagnostic} from './Diagnostic.jsx';
import {getJson} from './diagnostic';
const fmt=n=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(n);
const icon=L.icon({iconUrl:markerUrl,iconRetinaUrl:markerRetinaUrl,shadowUrl:markerShadow,iconSize:[25,41],iconAnchor:[12,41]});
function MapView({city,point,parcels,isochrone,onPoint}){
 const parcelLayer=useRef(),isoLayer=useRef();
 const root=useRef(),map=useRef(),marker=useRef(),callback=useRef(onPoint);callback.current=onPoint;
 const [tileError,setTileError]=useState(false);
 useEffect(()=>{
 const m=L.map(root.current,{zoomControl:false,scrollWheelZoom:false}).setView([45.758,4.8351],12);map.current=m;
 L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).on('tileerror',()=>setTileError(true)).on('tileload',()=>setTileError(false)).addTo(m);
 L.control.scale({imperial:false,position:'bottomright'}).addTo(m);
 m.on('click',e=>callback.current(e.latlng));
 return()=>{m.remove();map.current=null;};
 },[]);
 useEffect(()=>{if(!city||!map.current||point)return;const [lon,lat]=city.centre.coordinates;const z=city.surface>25000?10:city.surface>8000?11:12;map.current.setView([lat,lon],z);if(marker.current)marker.current.remove();marker.current=L.marker([lat,lon],{icon}).addTo(map.current).bindTooltip(city.nom,{direction:'top',offset:[0,-38]});},[city,point]);
 useEffect(()=>{if(!point||!map.current)return;if(marker.current)marker.current.remove();marker.current=L.marker([point.lat,point.lon],{icon}).addTo(map.current);map.current.setView([point.lat,point.lon],17);},[point]);
 useEffect(()=>{if(!map.current)return;if(parcelLayer.current)parcelLayer.current.remove();if(parcels.length)parcelLayer.current=L.geoJSON(parcels,{style:{color:'#da643d',weight:2,fillOpacity:.12}}).addTo(map.current);},[parcels]);
 useEffect(()=>{if(!map.current)return;if(isoLayer.current)isoLayer.current.remove();if(isochrone){isoLayer.current=L.geoJSON(isochrone,{style:{color:'#265de1',weight:2,fillOpacity:.15}}).addTo(map.current);map.current.fitBounds(isoLayer.current.getBounds(),{padding:[35,35]});}},[isochrone]);
 return <section className="map-wrap" aria-label="Carte interactive"><div ref={root} className="map"/><div className="north"><Compass size={24}/><span>N</span></div><div className="map-controls"><button aria-label="Zoomer" onClick={()=>map.current.zoomIn()}><Plus/></button><button aria-label="Dézoomer" onClick={()=>map.current.zoomOut()}><Minus/></button><button aria-label="Recentrer sur la commune" onClick={()=>{if(point)map.current.setView([point.lat,point.lon],17);else if(city){const [x,y]=city.centre.coordinates;map.current.setView([y,x],12);}}}><Crosshair/></button></div><div className="map-hint"><MapPin size={15}/> Cliquez sur un lieu précis pour l’analyser</div>{tileError&&<div className="map-error" role="status">Le fond de carte est momentanément indisponible.</div>}</section>
}
export function App(){
 const [all,setAll]=useState([]),[city,setCity]=useState(null),[query,setQuery]=useState(''),[open,setOpen]=useState(false),[index,setIndex]=useState(-1),[error,setError]=useState(''),[loading,setLoading]=useState(true),[detail,setDetail]=useState(false),[pointBusy,setPointBusy]=useState(false);
 const [point,setPoint]=useState(null),[parcels,setParcels]=useState([]),[isochrone,setIsochrone]=useState(null),[addresses,setAddresses]=useState([]),[addressBusy,setAddressBusy]=useState(false),[addressError,setAddressError]=useState('');
 const dialog=useRef(),input=useRef(),pointRequest=useRef(0);
 useEffect(()=>{fetch('/communes.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{const list=data.map(c=>({...c,key:normalize(c.nom)}));setAll(list);const code=new URLSearchParams(location.search).get('commune');const c=list.find(c=>c.code===(code||'69123'))||list.find(c=>c.code==='69123');setCity(c);setQuery(c.nom);}).catch(()=>setError('Impossible de charger les communes. Rechargez la page pour réessayer.')).finally(()=>setLoading(false));},[]);
 const results=useMemo(()=>[...searchCommunes(all,query),...addresses],[all,query,addresses]);
 useEffect(()=>{if(!open||query.trim().length<4){setAddresses([]);setAddressBusy(false);return;}const controller=new AbortController();setAddresses([]);setAddressBusy(true);setAddressError('');const timer=setTimeout(async()=>{try{const d=await getJson('https://data.geopf.fr/geocodage/search?'+new URLSearchParams({q:query,limit:'5',index:'address'}),{signal:controller.signal});if(!controller.signal.aborted)setAddresses((d.features||[]).filter(f=>{const dep=f.properties.depcode;return dep==='2A'||dep==='2B'||(/^\d{2}$/.test(dep)&&Number(dep)<=95);}).map((f,i)=>({address:true,code:'address-'+i,nom:f.properties.label,departement:{nom:'Adresse'},codeDepartement:f.properties.depcode,codesPostaux:[f.properties.postcode].filter(Boolean),lon:f.geometry.coordinates[0],lat:f.geometry.coordinates[1]})));}catch{if(!controller.signal.aborted)setAddressError('Recherche d’adresses indisponible ; les communes restent accessibles.');}finally{if(!controller.signal.aborted)setAddressBusy(false);}},350);return()=>{clearTimeout(timer);controller.abort();};},[query,open]);
 function select(c){if(!c)return;if(c.address){setOpen(false);setQuery(c.nom);onPoint({lat:c.lat,lng:c.lon,label:c.nom});return;}setPoint(null);setParcels([]);setIsochrone(null);pointRequest.current++;setPointBusy(false);setCity(c);setQuery(c.nom);setOpen(false);setIndex(-1);setError('');const url=new URL(location.href);url.searchParams.set('commune',c.code);history.replaceState({},'',url);}
 async function onPoint({lat,lng,label}){const id=++pointRequest.current;setPointBusy(true);setError('');try{const d=await getJson(`https://geo.api.gouv.fr/communes?lat=${lat}&lon=${lng}&fields=code`);if(id!==pointRequest.current)return;const c=all.find(c=>c.code===d[0]?.code);if(c){setCity(c);setPoint({lat,lon:lng,label:label||'Point sélectionné sur la carte'});setParcels([]);setIsochrone(null);setQuery(label||c.nom);setOpen(false);const url=new URL(location.href);url.searchParams.set('commune',c.code);history.replaceState({},'',url);}else setError('Sélectionnez un lieu situé dans une commune de France métropolitaine.');}catch{if(id===pointRequest.current)setError('La localisation du point est indisponible. Réessayez dans quelques instants.');}finally{if(id===pointRequest.current)setPointBusy(false);}}
 function showDetail(){if(!point){setError('Zoomez puis cliquez sur un point de la carte, ou recherchez une adresse précise.');return;}setDetail(true);dialog.current.showModal();}
 return <main>
 <header className="masthead"><a className="brand" href="./" aria-label="CartoKob, accueil">CartoKob<span>COMPRENDRE LES TERRITOIRES<br/>POUR AGIR DEMAIN</span></a>
 <div className="search-area"><form role="search" onSubmit={e=>{e.preventDefault();if(results.length)select(results[index>=0&&index<results.length?index:0]);else setOpen(true);}}><div className="search-field"><MagnifyingGlass size={24}/><input ref={input} aria-label="Rechercher une adresse, une commune ou un code postal" role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls="results" aria-activedescendant={index>=0?`result-${index}`:undefined} value={query} placeholder="Une adresse, une commune…" disabled={loading} onFocus={()=>setOpen(true)} onBlur={()=>setTimeout(()=>setOpen(false),150)} onChange={e=>{setQuery(e.target.value);setOpen(true);setIndex(-1);}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setIndex(i=>Math.min(i+1,results.length-1));}if(e.key==='ArrowUp'){e.preventDefault();setIndex(i=>Math.max(0,i-1));}if(e.key==='Escape')setOpen(false);}}/>{query&&<button type="button" aria-label="Effacer la recherche" onClick={()=>{setQuery('');input.current.focus();}}><X size={20}/></button>}</div><button className="search-go" aria-label="Rechercher" disabled={loading}><ArrowRight size={27}/></button></form>
 <p className="search-help">{loading?'Chargement des communes…':`${fmt(all.length)} communes · France métropolitaine, Corse comprise`}</p>
 {open&&query&&<ul id="results" role="listbox" className="results">{results.map((c,i)=><li id={`result-${i}`} key={c.code} role="option" aria-selected={i===index} onMouseDown={e=>e.preventDefault()} onClick={()=>select(c)} className={i===index?'active':''}><div><strong>{c.nom}</strong><span>{c.departement.nom} · {c.codeDepartement}</span></div><small>{c.codesPostaux.slice(0,2).join(', ')}</small></li>)}{addressBusy&&<li className="empty">Recherche d’adresses…</li>}{addressError&&<li className="empty">{addressError}</li>}{!results.length&&!addressBusy&&<li className="empty">Aucun résultat. Essayez une adresse, une commune ou un code postal.</li>}</ul>}</div>
 <div className="brand-note"><span>CARTOGRAPHIE<br/>TERRITOIRES<br/>PERSPECTIVES</span><img src="/france.svg" alt="France métropolitaine"/><span>DES LIEUX<br/>PLUS CLAIRS,<br/>DES CHOIX<br/>PLUS ÉCLAIRÉS.</span></div></header>
 <div role="status" className={error||pointBusy?'status visible':'status'}>{pointBusy?'Recherche de la commune…':error}</div>
 <MapView city={city} point={point} parcels={parcels} isochrone={isochrone} onPoint={onPoint}/>
 {city&&<section className="summary" aria-live="polite"><div className="place"><p className="eyebrow">AIDE À LA DÉCISION</p><div className="place-title"><h1 className={city.nom.length>16?'long':city.nom.length>9?'medium':''}>{city.nom}</h1><span>{city.codeDepartement}</span></div><p className="place-sub">{point?point.label:city.departement.nom}<br/><span className="point-instruction">{point?`${point.lat.toFixed(5)}° N · ${point.lon.toFixed(5)}° E` : "Choisissez un point pour lancer le diagnostic."}</span></p></div>
 <article className="fact"><span className="fact-icon green"><Users size={28}/></span><div><p className="eyebrow">VIE LOCALE</p><h2>{city.population!=null?`${fmt(city.population)} habitants`:'Population non disponible'}</h2><p>Une première lecture de la commune et de son échelle.</p><a href="https://geo.api.gouv.fr/" target="_blank" rel="noreferrer">Population · API Découpage administratif <ArrowUpRight size={13}/></a></div></article>
 <article className="fact"><span className="fact-icon peach"><MapTrifold size={28}/></span><div><p className="eyebrow">GÉOGRAPHIE</p><h2>{city.surface!=null?`${fmt(city.surface/100)} km² de territoire`:'Un territoire à explorer'}</h2><p>{city.population!=null&&city.surface>0?`${fmt(city.population/(city.surface/100))} habitants par km².`:'Explorez la commune sur la carte.'}<br/>Code commune : {city.code}.</p><span className="data-note">Repères communaux</span></div></article></section>}
 <footer><div className="signature">Atlas éditorial <span>—</span> CartoKob</div><button className="primary" disabled={!city} onClick={showDetail}>{point?"Analyser ce point":"Choisir un point"} <ArrowRight size={20}/></button><span className="edition">Édition métropolitaine <span>·</span> Prototype</span></footer>
 <dialog ref={dialog} onClose={()=>setDetail(false)} aria-labelledby="detail-title"><button className="close" aria-label="Fermer le portrait" onClick={()=>dialog.current.close()}><X size={24}/></button>{city&&point&&detail&&<Diagnostic key={`${point.lat},${point.lon}`} city={city} point={point} onGeometry={setParcels} onIsochrone={setIsochrone}/>}</dialog>
 </main>
}
