import React,{useEffect,useState,useRef} from 'react';
import {ArrowUpRight,ArrowClockwise,DownloadSimple,PersonSimpleWalk} from '@phosphor-icons/react';
import {loadDiagnostic,getJson,featureList} from './diagnostic';
function label(feature,key){const p=feature.properties||{};if(key==='parcel')return `Parcelle ${p.section||''} ${p.numero||''} · ${p.contenance??'—'} m²`;return p.libelle||p.libelong||p.SITENAME||p.sitename||p.NOM||p.nom||p.nom_site||p.id_mnhn||'Périmètre identifié';}
export function Diagnostic({city,point,onGeometry,onIsochrone}){
 const walkController=useRef(null);
 useEffect(()=>()=>walkController.current?.abort(),[]);
 const [data,setData]=useState({}),[retry,setRetry]=useState(0),[walk,setWalk]=useState('idle');
 useEffect(()=>{const controller=new AbortController();setData({});setWalk('idle');loadDiagnostic(point,city.code,{signal:controller.signal,onUpdate:(key,result)=>{if(!controller.signal.aborted){setData(d=>({...d,[key]:result}));if(key==='parcel'&&result.status==='success')onGeometry(result.items);}}});return()=>controller.abort();},[point,city.code,retry]);
 const [walkError,setWalkError]=useState('');
 async function isochrone(){walkController.current?.abort();const controller=new AbortController();walkController.current=controller;setWalk('loading');setWalkError('');try{const d=await getJson('https://valhalla1.openstreetmap.de/isochrone',{signal:controller.signal,method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({locations:[{lat:point.lat,lon:point.lon}],costing:'pedestrian',contours:[{time:15,color:'265de1'}],polygons:true,generalize:25})});if(controller.signal.aborted)return;if(!featureList(d).length)throw Error();onIsochrone(d);setWalk('success');}catch{if(controller.signal.aborted)return;setWalk('error');setWalkError('Le calcul piéton est indisponible. Réessayez dans quelques instants.');}}
 function exportReport(){const lines=['CartoKob — Aide à la décision',city.nom,point.label||'Point sélectionné',`${point.lat}, ${point.lon}`,`Consultation : ${new Date().toLocaleString('fr-FR')}`,'',...Object.values(data).flatMap(d=>[`${d.title} — ${d.scope}`,`Source : ${d.source}`,`URL : ${d.url}`,d.status==='success'?(d.items.length?d.items.map(x=>typeof x==='string'?x:label(x,d.key)).join('\n'):'Aucun objet retourné par la source. Cela ne prouve pas une absence de contrainte.'):d.status==='error'?'Service indisponible':'Consultation en cours','']),'Les risques GASPAR concernent la commune ; ils ne caractérisent pas l’exposition exacte du point. Vérifier les documents opposables.'];const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`cartokob-${city.code}-diagnostic.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <><p className="eyebrow">CARTOKOB · AIDE À LA DÉCISION</p><h2 id="detail-title">{city.nom}</h2><p className="dialog-intro">{point.label||'Point sélectionné sur la carte'}<br/><span>{point.lat.toFixed(5)}° N · {point.lon.toFixed(5)}° E</span></p><div className="report-actions"><button onClick={()=>setRetry(x=>x+1)}><ArrowClockwise/> Actualiser</button><button onClick={exportReport} disabled={Object.keys(data).length===0||Object.values(data).some(d=>d.status==='loading')}><DownloadSimple/> Exporter la synthèse</button></div>
 <p className="report-note">Lecture au point, complétée par le contexte communal. Un résultat vide ou indisponible ne signifie pas absence de risque ou de règle.</p>
 <div className="diagnostic-sections">{Object.values(data).map(d=><section className="diagnostic-section" key={d.key}><div className="diagnostic-heading"><h3>{d.title}</h3><span className={`source-status ${d.status}`}>{d.status==='loading'?'Consultation…':d.status==='error'?'Indisponible':'Source consultée'}</span></div><p className="scope">{d.scope}</p>{d.status==='error'?<p>Le service n’a pas répondu correctement. Aucun résultat ne peut être conclu.</p>:d.status==='loading'?<p>Interrogation de la source…</p>:d.items.length?<ul>{d.items.map((x,i)=><li key={i}>{typeof x==='string'?x:label(x,d.key)}</li>)}</ul>:<p>Aucun objet retourné à cet emplacement par cette source.</p>}{d.truncated&&<p>Résultats partiels : consulter la source pour la liste complète.</p>}{d.key==='risks'&&<p className="caution">Ces risques sont recensés dans la commune, sans établir l’exposition de cette parcelle.</p>}<a className="source-link" href={d.url} target="_blank" rel="noreferrer">{d.source} <ArrowUpRight size={13}/></a>{d.queriedAt&&<small className="query-time">Consulté à {new Date(d.queriedAt).toLocaleTimeString('fr-FR')} · millésime selon la source</small>}</section>)}</div>
 <section className="diagnostic-section"><h3>Accessibilité à pied</h3><p>Calculer la zone atteignable en 15 minutes autour du point sélectionné, selon le réseau OpenStreetMap.</p><button className="walk-button" onClick={isochrone} disabled={walk==='loading'}><PersonSimpleWalk/>{walk==='loading'?'Calcul en cours…':walk==='success'?'Recalculer les 15 minutes':'Voir les 15 minutes à pied'}</button>{walk==='success'&&<p>Zone affichée sur la carte. Fermez le panneau pour l’explorer.</p>}{walkError&&<p role="status">{walkError}</p>}<p className="scope">Estimation Valhalla / OpenStreetMap ; conditions réelles et accessibilité PMR non vérifiées.</p></section>
 <div className="source-links"><a href={`https://www.geoportail-urbanisme.gouv.fr/map/#tile=1&lon=${point.lon}&lat=${point.lat}&zoom=17`} target="_blank" rel="noreferrer">Consulter les documents d’urbanisme <ArrowUpRight/></a><a href={`https://www.georisques.gouv.fr/api/v1/rapport_pdf?latlon=${point.lon},${point.lat}`} target="_blank" rel="noreferrer">Rapport officiel Géorisques au point <ArrowUpRight/></a></div><p className="provenance">Première version nationale. Le diagnostic ne couvre pas encore le logement, les nuisances sonores, le bâti, les servitudes et l’ensemble des protections environnementales de l’outil d’origine. Les données sont à confronter aux documents en vigueur.</p></>
}
