import React,{useEffect,useState,useRef} from 'react';
import {ArrowUpRight,ArrowClockwise,DownloadSimple,PersonSimpleWalk,CaretDown} from '@phosphor-icons/react';
import {loadDiagnostic,getJson,featureList} from './diagnostic.js';
import {MarketSection} from './MarketSection.jsx';
import {featureLabel} from './feature-label.js';
export {featureLabel} from './feature-label.js';

function SourceItems({items,sourceKey}){
 const render=(x,i)=><li key={i}>{typeof x==='string'?x:featureLabel(x,sourceKey)}</li>;
 return <><ul>{items.slice(0,5).map(render)}</ul>{items.length>5&&<details className="source-more"><summary>Voir les {items.length-5} autres résultats</summary><ul>{items.slice(5).map(render)}</ul></details>}</>;
}
export function Diagnostic({city,point,onGeometry,onIsochrone}){
 const walkController=useRef(null);
 useEffect(()=>()=>walkController.current?.abort(),[]);
 const [data,setData]=useState({}),[retry,setRetry]=useState(0),[walk,setWalk]=useState('idle');
 useEffect(()=>{const controller=new AbortController();setData({});setWalk('idle');setWalkError('');onGeometry([]);onIsochrone(null);walkController.current?.abort();loadDiagnostic(point,city.code,{signal:controller.signal,onUpdate:(key,result)=>{if(!controller.signal.aborted){setData(d=>({...d,[key]:result}));if(key==='parcel'&&result.status==='success')onGeometry(result.items);}}});return()=>controller.abort();},[point,city.code,retry]);
 const [walkError,setWalkError]=useState('');
 async function isochrone(){walkController.current?.abort();const controller=new AbortController();walkController.current=controller;setWalk('loading');setWalkError('');try{const d=await getJson('https://valhalla1.openstreetmap.de/isochrone',{signal:controller.signal,method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({locations:[{lat:point.lat,lon:point.lon}],costing:'pedestrian',contours:[{time:15,color:'265de1'}],polygons:true,generalize:25})});if(controller.signal.aborted)return;if(!featureList(d).length)throw Error();onIsochrone(d);setWalk('success');}catch{if(controller.signal.aborted)return;setWalk('error');setWalkError('Le calcul piéton est indisponible. Réessayez dans quelques instants.');}}
 const [pdfError,setPdfError]=useState(''),[pdfBusy,setPdfBusy]=useState(false);
 async function exportReport(){
  setPdfError('');
  const tab=window.open('about:blank','_blank');
  if(!tab){setPdfError('Autorisez les fenêtres surgissantes pour ouvrir la synthèse PDF, puis réessayez.');return;}
  tab.opener=null;tab.document.title='CartoKob - Préparation du PDF';tab.document.body.textContent='Préparation de votre synthèse CartoKob…';setPdfBusy(true);
  try{const {createDiagnosticPdf}=await import('./report-pdf.js');const pdf=createDiagnosticPdf({city,point,data});const url=URL.createObjectURL(pdf.output('blob'));if(tab.closed){URL.revokeObjectURL(url);return;}tab.location.replace(url);setTimeout(()=>URL.revokeObjectURL(url),600000);}
  catch{if(!tab.closed)tab.close();setPdfError('La synthèse PDF n’a pas pu être créée. Réessayez.');}
  finally{setPdfBusy(false);}
 }

 return <><p className="eyebrow">DIAGNOSTIC DU LIEU</p><h2 id="detail-title">{data.parcel?.items?.length===1?"Votre parcelle":"Votre sélection"} à {city.nom}.</h2><p className="dialog-intro">{point.label||'Point sélectionné sur la carte'}<br/><span>{point.lat.toFixed(5)}° N · {point.lon.toFixed(5)}° E</span></p><div className="report-actions"><button onClick={()=>setRetry(x=>x+1)}><ArrowClockwise/> Actualiser</button><button onClick={exportReport} disabled={pdfBusy||Object.keys(data).length===0||Object.values(data).some(d=>d.status==='loading')}><DownloadSimple/> {pdfBusy?'Préparation…':'Ouvrir la synthèse PDF'}</button></div>{pdfError&&<p role="alert" className="data-warning">{pdfError}</p>}
 <p className="report-note">Lecture au point sélectionné, complétée par le contexte communal. Les zonages ne sont pas testés sur l’intégralité de la parcelle. Un résultat vide ou indisponible ne signifie pas absence de risque ou de règle. Le zonage affiché ne suffit pas à établir la constructibilité d’un projet.</p>
 <div className="diagnostic-sections">{Object.values(data).map(d=><details className="diagnostic-section" key={d.key} open={d.key==='parcel'||d.key==='urban'}><summary className="diagnostic-heading"><h3>{d.title}</h3><span className={`source-status ${d.status}`}>{d.status==='loading'?'Consultation…':d.status==='error'?'Indisponible':'Source consultée'}</span><CaretDown className="details-chevron" size={14}/></summary><p className="scope">{d.scope}</p>{d.status==='error'?<p>Le service n’a pas répondu correctement. Aucun résultat ne peut être conclu.</p>:d.status==='loading'?<p>Interrogation de la source…</p>:d.items.length?<SourceItems items={d.items} sourceKey={d.key}/>:<p>Aucun objet retourné à cet emplacement par cette source.</p>}{d.truncated&&<p>Résultats partiels : consulter la source pour la liste complète.</p>}{d.key==='risks'&&<p className="caution">Ces risques sont recensés dans la commune, sans établir l’exposition de cette parcelle.</p>}<a className="source-link" href={d.url} target="_blank" rel="noreferrer">{d.source} <ArrowUpRight size={13}/></a>{d.queriedAt&&<small className="query-time">Consulté à {new Date(d.queriedAt).toLocaleTimeString('fr-FR')} · millésime selon la source</small>}</details>)}</div>
 <section className="diagnostic-section"><h3>Accessibilité à pied</h3><p>Calculer la zone atteignable en 15 minutes autour du point sélectionné, selon le réseau OpenStreetMap.</p><button className="walk-button" onClick={isochrone} disabled={walk==='loading'}><PersonSimpleWalk/>{walk==='loading'?'Calcul en cours…':walk==='success'?'Recalculer les 15 minutes':'Voir les 15 minutes à pied'}</button>{walk==='success'&&<p>Zone affichée sur la carte. Explorez-la sur la carte.</p>}{walkError&&<p role="status">{walkError}</p>}<p className="scope">Estimation Valhalla / OpenStreetMap ; conditions réelles et accessibilité PMR non vérifiées.</p></section>
 {data.parcel?.items?.length===1&&data.parcel.items[0].properties?.idu&&<MarketSection city={city} parcelId={data.parcel.items[0].properties.idu}/>}<div className="source-links"><a href={`https://www.geoportail-urbanisme.gouv.fr/map/#tile=1&lon=${point.lon}&lat=${point.lat}&zoom=17`} target="_blank" rel="noreferrer">Consulter les documents d’urbanisme <ArrowUpRight/></a><a href={`https://www.georisques.gouv.fr/api/v1/rapport_pdf?latlon=${point.lon},${point.lat}`} target="_blank" rel="noreferrer">Rapport officiel Géorisques au point <ArrowUpRight/></a></div><p className="provenance">Première version nationale. Le logement est décrit à l’échelle communale. La BDNB apporte des informations sur les groupes de bâtiments, dont un éventuel DPE associé à vérifier pour le logement concerné. Les nuisances sonores et certaines protections environnementales restent à intégrer. Les intersections sont calculées au point sélectionné, pas sur toute la surface cadastrale. Les données sont à confronter aux documents en vigueur.</p></>
}
