import React,{useEffect,useState} from 'react';
import {loadLocalLife} from './local-life.js';
import {fmt} from './territory.js';
import {SourceNotes} from './SourceNotes.jsx';
function Block({title,item,children}){return <section className="portrait-section"><p className="section-eyebrow">{title}</p>{!item||item.status==='loading'?<p role="status">Chargement…</p>:item.status==='error'?<p className="data-warning">Données indisponibles</p>:children}</section>;}
function Facts({rows}){return <dl className="readable-facts">{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>;}
const price=p=>p?`${fmt(p.value,2)} € TTC/m³`:'Non disponible';
const rentValue=r=>r?.scope==='arrondissements'?`${fmt(r.minimum,1)}–${fmt(r.maximum,1)}`:fmt(r?.value,1);
const percent=v=>v==null?'Non disponible':fmt(v,1)+' %';
export function LocalLife({city}){
 const [state,setState]=useState({});useEffect(()=>{const controller=new AbortController();setState({});loadLocalLife(city,{signal:controller.signal,onUpdate:(key,value)=>setState(s=>({...s,[key]:value}))});return()=>controller.abort();},[city.code]);
 const water=state.water?.data,transport=state.transport?.data,services=state.services?.data,energy=state.energy?.data,rents=state.rents?.data?.values,schools=state.schools?.data;
 return <div className="local-life">
 <Block title="Loyers estimés · 2025" item={state.rents}>{rents?<><Facts rows={[["Appartement · €/m²/mois CC",rentValue(rents.apartment)],["Maison · €/m²/mois CC",rentValue(rents.house)]]}/><p className="market-subtitle">{[rents.apartment,rents.house].some(r=>r?.scope==='arrondissements')?'Fourchette des estimations par arrondissement. ' :[rents.apartment,rents.house].some(r=>r?.scope==='maille')?'Estimation sur un groupe de communes pour au moins un type de bien.':'Estimation communale.'} {[rents.apartment,rents.house].some(r=>r&&((r.r2!=null&&r.r2<0.5)||(r.observations!=null&&r.observations<30)))?'Fiabilité limitée : peu d’annonces ou modèle moins précis.':''}</p></>:<p>Estimation non disponible pour ce code communal.</p>}</Block>
 <Block title="Écoles et établissements scolaires" item={state.schools}>{schools&&<Facts rows={schools.rows.map(r=>[r.type_etablissement||'Autres établissements',fmt(r.count)])}/>}</Block>
 <Block title="Prix et qualité de l’eau" item={state.water}>{water&&<><Facts rows={[[`Eau potable · ${water.drinking?.priceYear||'tarif non renseigné'}`,price(water.drinking)],[`Assainissement collectif · ${water.sewer?.priceYear||'tarif non renseigné'}`,price(water.sewer)],[`Conformité microbiologique · ${water.year}`,percent(water.microbiology)],[`Conformité physico-chimique · ${water.year}`,percent(water.chemistry)]]}/><p className="market-subtitle">Tarifs de référence pour 120 m³/an.</p></>}</Block>
 <Block title="Transports en commun" item={state.transport}>{transport&&<><Facts rows={[["Noms d’arrêts recensés",fmt(transport.names.length)],["Jeux de données de transport",fmt(transport.networks.length)]]}/>{transport.names.length?<><div className="transport-stops">{transport.names.map(name=><span key={name}>{name}</span>)}</div><div className="transport-networks">{transport.networks.map(n=><p key={n.id}>{n.name}</p>)}</div></>:<p>Aucun arrêt retourné par la base consultée.</p>}<p className="market-subtitle">Inventaire d’arrêts · lignes et horaires non intégrés.</p></>}</Block>
 <Block title="Services publics et contacts" item={state.services}>{services&&<><Facts rows={[["Services référencés dans la commune",fmt(services.total)]]}/>{services.services.map(s=><article className="public-contact" key={s.id}><h4>{s.name}</h4>{s.address&&<p>{s.address}</p>}{s.phone&&<a href={'tel:'+s.phone.replace(/[^+\d]/g,'')}>{s.phone}</a>}</article>)}{!services.services.length&&<p>Aucun contact mairie, France Services ou sécurité retourné.</p>}{services.partial&&<p className="data-warning">Liste de contacts partielle</p>}</>}</Block>
 <Block title={`Électricité résidentielle${energy?.year?' · '+energy.year:''}`} item={state.energy}>{energy&&<Facts rows={[["Consommation annuelle",energy.total==null?'Non disponible':fmt(energy.total)+' MWh'],["Sites de consommation",fmt(energy.sites)]]}/>}</Block>
 <SourceNotes><h4>Habitat et vie quotidienne</h4><p><a href="https://www.data.gouv.fr/datasets/carte-des-loyers-indicateurs-de-loyers-dannonce-par-commune-en-2025" target="_blank" rel="noreferrer">Estimations ANIL, à partir des données du Groupe SeLoger et de leboncoin · 2025</a> · Loyers d’annonces non meublées, charges comprises (CC), pas loyers garantis. Appartement de référence 52 m², maison 92 m². Géographie communale 2025.</p>{rents&&<p>{[['Appartement',rents.apartment],['Maison',rents.house]].filter(([,r])=>r).map(([label,r])=>r.scope==='arrondissements'?`${label} : ${r.entries.map(e=>`${e.code} : ${fmt(e.value,1)} €/m²/mois`).join(' ; ')}${r.partial?' (couverture partielle)':''}.`:`${label} : ${r.scope}, ${fmt(r.observations)} annonces communales ; intervalle de prédiction ${fmt(r.low,1)}–${fmt(r.high,1)} €/m²/mois.`).join(' ')}</p>}{schools&&<p><a href={schools.source} target="_blank" rel="noreferrer">Annuaire de l’Éducation nationale · établissements ouverts</a></p>}{water&&<p><a href={water.source} target="_blank" rel="noreferrer">SISPEA · fiche communale {water.year}</a> · Tarifs au 1er janvier {water.year+1}, référence de 120 m³/an. Eau potable et assainissement séparés ; aucun total estimé. Les valeurs non univoques restent non disponibles. Conformité annuelle des services, pas un bulletin au robinet du bien.</p>}<p><a href="https://transport.data.gouv.fr/explore/gtfs-stops" target="_blank" rel="noreferrer">Point d’accès national · arrêts GTFS</a> · Base expérimentale, pouvant être incomplète ou ancienne. Filtrage dans le contour communal ; noms distincts, pas un décompte garanti des arrêts physiques. Un réseau publié peut comprendre des services scolaires. Ni fréquence ni desserte actuelle garantie.</p>{services&&<><p><a href={services.source} target="_blank" rel="noreferrer">Annuaire Service-Public · DILA</a> · Organismes situés dans la commune, pas périmètres de compétence.</p>{services.services.map(s=><p key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.name}</a>{s.updated?' · '+s.updated:''}</p>)}</>}{energy&&<p><a href={energy.source} target="_blank" rel="noreferrer">Agence ORE · électricité résidentielle {energy.year}</a> · Consommations agrégées par commune, pas une facture ou une estimation pour le bien.</p>}</SourceNotes>
 </div>;
}
